### ISSUE TITLE
site crashes when people enter too many digits in the custom trees

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet/planet-webapp#118]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/27153515/91651254-1838c380-eaa8-11ea-9534-cdd1a10f777e.gif)

Stripe allows max of 8 digits for USD/EUR . Maybe only allow upto 12 digits so we might be able to cover people who donate with other currencies?

**Comment by harshvitra** [comment]
@nirali25parekh 

Please check this
Also don't allow 0

check https://react-hook-form.com/get-started/#Applyvalidation
