### ISSUE TITLE
Web app - project scroll bar - scrolling broken

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet/planet-webapp#192]
beta.plant-for-the-planet.org has a broken project scroll bar (Firefox and Edge)

On the current beta beta beta.plant-for-the-planet.org

Parts of the Bug:

1 Unstable Dragging (firefox only)
If you drag the scroll bar it jumps all over the place.

2 **Overshooting En

ds** (Firefox and Edge)
You can overshoot the end of the scrolling bar (which sends you back to the middle).

3 Scroll -> Drag -> Scroll Jump (Firefox and Edge)
If you scroll via mouse wheel, then drag yourself to a new part of the bar, then scroll again, it will teleport the bar back to where you last scrolled (instead of scrolling from hte current position)

4 Slow Scrolling (Firefox, Edge to a lesser degree)
On Firefox the increments by which you scroll are very tiny so it takes very long to get to the next project via mouse wheel.
On Edge it is okay.

Videos
Here are 2 videos of me showing the behaviour.

Firefox
https://youtu.be/5WIHNPcGEZ0

Edge
https://youtu.be/hcjI_X0aHr4

**Comment by Plant-for-the-Planet** [comment]
Fixed by #193
