### ISSUE TITLE
Remaining Items from Donation Share PR

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet/planet-webapp#197]
- [ ] Need to increase the size/resolution of the downloaded image.

- [ ] When clicking the twitter icon or the email icon on my android it opens the share card instead of twitter even though I have the twitter app installed (same for insta and fb but I don't have those apps)

- [ ] In the download the logo and the trillion trees is super low res while the adjusted text looks great. But I think you know that
 
- [ ] The plant trees at www.trillion does not need "www." And it should be right at the bottom of the card. Ideally, in the card preview it would be a bit further up (as it is now) to make space for the share buttons, but once you actually download it, the text would be further down. Is that possible?

**Comment by harshvitra** [comment]
@nirali25parekh 

For 1 and 3 use high res image I have shared on slack
Create a different component and hide it
