### ISSUE TITLE
Fixes to Tax Deduction

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet/planet-webapp#215]
<img width="1010" alt="Screen Shot 2020-09-17 at 5 19 07 PM" src="https://user-images.githubusercontent.com/6512255/93496529-9baf3d00-f90f-11ea-9bee-f4e71af3b3d6.png">

Use the text below:

`You will receive a tax deduction receipt for {{CountryName}} in time for tax returns.`

Ideally we want to allow dropdown after {{countryName}} in future;

and show
`No tax deduction is available for {{currentCountry}}`

show a dropdown of countries for tax deductions

![WhatsApp Image 2020-09-17 at 5 29 10 PM](https://user-images.githubusercontent.com/6512255/93496812-f9438980-f90f-11ea-85ff-abb61e82a6f9.jpeg)

![WhatsApp Image 2020-09-17 at 5 29 10 PM (1)](https://user-images.githubusercontent.com/6512255/93496819-fcd71080-f90f-11ea-8e42-9a0a44941a7a.jpeg)

**Comment by harshvitra** [comment]
@ankitecd along with this add key also in the map function of currency to remove the error
