### ISSUE TITLE
CORS issue loading web font

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet/planet-webapp#217]
**Describe the bug**

Access to font at 'https://cdn.pp.eco/media/fonts/opensans/OpenSans-Bold.woff2' from origin 'https://trees.salesforce.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://trees.salesforce.com/
2. See error in console

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

**Comment by norbertschuler** [comment]
Strange thing about this is, the other fonts have been loaded:

<img width="714" alt="Bildschirmfoto 2020-09-17 um 19 16 03" src="https://user-images.githubusercontent.com/1532418/93504800-3164bf80-f944-11ea-846c-00e6a89c3e9e.png">

**Comment by Plant-for-the-Planet** [comment]
@norbertschuler 

Cleared the CDN Cache, seems to work fine now.
<img width="1345" alt="Screen Shot 2020-09-17 at 7 43 48 PM" src="https://user-images.githubusercontent.com/6512255/93507568-28f98e00-f91e-11ea-8761-dbda66017b61.png">
