### ISSUE TITLE
Achieve pixel perfect design for the bottom navbar

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet/planet-webapp#230]
Achieve pixel perfect design for the bottom navbar
<img width="742" alt="Screen Shot 2020-09-18 at 9 05 18 PM" src="https://user-images.githubusercontent.com/25605193/93635645-473fb680-fa10-11ea-86aa-5532d18da445.png">

**Comment by Plant-for-the-Planet** [comment]
has been fixed
