### ISSUE TITLE
Current Issues to Fix

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet/planet-webapp#34]
- [x] Color of scrollbar [make it same as color of tree target progress bar]

- [x] Fix issue where planted and org falls below line.

This could probably be fixed by having same text string `{{treecount_planted}}planted . {{country}}`
<img width="866" alt="Screen Shot 2020-08-04 at 4 41 58 PM" src="https://user-images.githubusercontent.com/5401575/89307487-6c9b7f80-d671-11ea-8054-3c58d2aeda09.png">

- [x] Remove Improve this Map from the Map `.mapbox-improve-map{display:none;}`

- [x] Change yellow color for unavailable images to green

- [x] Set zoom level to 1.4 for main page

- [ ] On scroll with mouse on map or any space, scroll the items on the tabs on left.

**Comment by sagararyal** [comment]
Zoom 2 [Single Project  Page ]

- [ ] Implement fly  to  a location when user clicks a project. zoom to zoom level 12 or 13 https://docs.mapbox.com/mapbox-gl-js/example/scroll-fly-to/ Clicking back should  fly back to zoom level 1.4

**Comment by sarveshpro** [comment]
Created #116 for remaining changes
