### ISSUE TITLE
New Topbar

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet/planet-webapp#73]
![image](https://user-images.githubusercontent.com/27153515/90474667-6f9f7100-e143-11ea-9542-298d9d0c3738.png)

this is incorrect.

**Comment by sagararyal** [comment]
If tenant  ≠ Plant-for-the-Planet

<img width="1226" alt="Screen Shot 2020-08-20 at 11 52 26 AM" src="https://user-images.githubusercontent.com/5401575/90755640-a01a1300-e2db-11ea-8f52-18d631322374.png">

If tenant = Plant-for-the-Planet

<img width="801" alt="Screen Shot 2020-08-20 at 11 53 29 AM" src="https://user-images.githubusercontent.com/5401575/90755765-ccce2a80-e2db-11ea-9bab-126a47ba41d4.png">
About us should follow same style as donate and other buttons

**Comment by sarveshpro** [comment]
@ankitecd, please resolve this issue in your UNEP PR

**Comment by harshvitra** [comment]
- [ ] Use Fontawesome icon without adding too much of bundle

**Comment by sarveshpro** [comment]
Done. Finally!
