### ISSUE TITLE
Zoom 2: Fit site bounds on the map 

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet/planet-webapp#85]
On Zoom 2 (Single Projects Page)

- [x] Use fitBounds to show a specific area of the map in view, regardless of the pixel size of the map.
https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/

- [x] Use flyto when user clicks next site on the map
https://docs.mapbox.com/mapbox-gl-js/example/flyto/

<img width="945" alt="Screen Shot 2020-08-20 at 12 53 16 PM" src="https://user-images.githubusercontent.com/5401575/90761723-1fabe000-e2e4-11ea-99c3-b29bc6460ecc.png">

- [x] Zoom 1 to Zoom 2 should be a flyto

**Comment by sarveshpro** [comment]
https://visgl.github.io/react-map-gl/docs/advanced/viewport-transition#example-transition-viewport-to-a-bounding-box
